# 기본 Node.js 이미지 사용 (알맞은 버전 선택)
FROM node:20-alpine
# 작업 디렉토리 설정
WORKDIR /app
# 프로젝트 소스 코드 복사
COPY package*.json ./
# 의존성 설치
RUN npm install
# 프로젝트 소스 코드 전체 복사
COPY . .
# 프로덕션 모드로 빌드
RUN npm run build
# 포트 설정 (필요에 따라 변경)
EXPOSE 3000
# 컨테이너 실행 명령
CMD ["npm", "start"]